pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo "Building from branch: ${env.BRANCH_NAME}"
            }
        }

        stage('Test') {
            steps {
                echo "Testing from branch: ${env.BRANCH_NAME}"
            }
        }
    }
}
